version: '3.7'

services:
  frontend:
    container_name: my-front
    build:
      context: frontend
      dockerfile: front.dev.Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app

  backend:
    container_name: my-back
    restart: always
    build:
      context: backend
      dockerfile: back.dev.Dockerfile
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./backend:/www
    links:
      - db
    depends_on:
      - frontend

  db:
    image: mysql:5.7
    container_name: my-back-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "qwerqwer123"
      MYSQL_DATABASE: "fullstack_test"
      MYSQL_USER: "wool"
      MYSQL_PASSWORD: "qwerqwer123"
    volumes:
      - /Users/oliver/socar-dev/docker_db/fullstack_mysql:/var/lib/mysql